### ISSUE TITLE
Impressive results! 

### ISSUE THREAD

**Issue by akanimax** [universome/epigraf#1]
Not an issue 😅. 
Cool results! So refreshing to see 3D GAN results on something other than faces and toy-cars 😆!
Looking forward to your code. 

Cheers!
@akanimax

P.S.  To the present owners of GitHub, perhaps it's a good time to introduce a comment feature 😄...

**Comment by universome** [comment]
Hi Animesh, thank you! :)

Yeah, I also believe the community should put more focus on fitting more complex-geometry datasets, especially for real data and single view per object (in our case, it is still synthetic and multiple views per object). Btw, In the README, there is a [link](https://www.dropbox.com/s/544w39moctyw8ch/rnf-code.zip?dl=0) to an un-refactored (but still decent) version of our code.

**Comment by akanimax** [comment]
Awesome! Sorry, but I have been through the pain of going through un-refactored (euphemism for ``shitty'' :laughing:) research codes :sweat_smile:. I'd wait for the refactored one. It's cool of you folks to refactor the code prior to release. A noble cause indeed! 
Cheers :)!

p.s. closing this #1 Issue, because it's not an issue technically.
