### ISSUE TITLE
dataset.json for ffhq

### ISSUE THREAD

**Issue by ghost** [universome/epigraf#11]
Hi ! 
Thank you for sharing this great work !
I was wondering if you could share the dataset.json corresponding to FFHQ (or how exactly to get the [yaw,pitch,roll] vector from the face_poses.zip from GRAM)
Thanks a lot !

**Comment by universome** [comment]
Hi! Here is the link to our FFHQ dataset: https://disk.yandex.ru/d/UmglE8U3YVbuLg
Note, that we removed 3 images from it since they had broken camera parameters (we took the camera parameters from GRAM).

**Comment by ghost** [comment]
This is great ! Thanks a lot for the quick reply !!

**Comment by trungdt880** [comment]
Hi, thanks again for the great work! Can you upload the json seperatedly? I have very bad internet hence download from the above links took days to complete :(
Otherwise can you tell me how do you represent the angle (radian, degree, 0-center,...)?
