### ISSUE TITLE
Release code about Megascans rendering scripts & instructions 

### ISSUE THREAD

**Issue by ja-yeon-kim** [universome/epigraf#8]
Hi, Thank you for your great work!

Do you have a plan for releasing code about the Megascan dataset?
It is a very interesting part of this paper.

Thank you.

**Comment by universome** [comment]
Hi, I am sorry for such a late response. We've just uploaded the rendering code, instructions and datasets [here](https://github.com/universome/megascans-rendering).

**Comment by ja-yeon-kim** [comment]
Thank you!
